controllers/BooksController.php
<?php

namespace app\controllers;

use app\models\Book;

class BooksController extends Encyclopedia
{
    /**
     * @var string Имя модели, которая соответствует выбранному контроллеру
     */
    protected static $name = 'app\models\Book';

    /**
     * @return string Действие для отображения страницы "Книги"
     */
    public function actionIndex()
    {
        $pages = Book::pagination(Book::findAllItems('countQuery'), 7);
        $models = Book::findAllItems('result', 7);
        $sort = Book::sort();

        return $this->render('index', [
            'models' => $models,
            'pages' => $pages,
            'sort' => $sort
        ]);
    }
}

controllers/CoursesController.php
<?php

namespace app\controllers;

use app\models\Course;

class CoursesController extends Encyclopedia
{
    /**
     * @var string Имя модели, которая соответствует выбранному контроллеру
     */
    protected static $name = 'app\models\Course';

    /**
     * @return string Действие для отображения страницы "Курсы"
     */
    public function actionIndex()
    {
        $pages = Course::pagination(Course::findAllItems('countQuery'), 7);
        $models = Course::findAllItems('result', 7);
        $sort = Course::sort();

        return $this->render('index', [
            'models' => $models,
            'pages' => $pages,
            'sort' => $sort
        ]);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use app\models\LoginForm;
use app\models\SignupForm;
use app\models\Book;
use app\models\Course;

class SiteController extends Encyclopedia
{
    /**
     * Отображение главной страницы
     *
     * @return string
     */
    public function actionIndex()
    {
        $model["books"] = Book::findAllItems();
        $model["courses"] = Course::findAllItems();
        return $this->render('index', [
            'model' => $model,
        ]);
    }

    /**
     * Действие для страницы аутентификации
     *
     * @return string
     */
    public function actionLogin()
    {
        // Логиним пользователя:
        $model = new LoginForm();
        // login() используется кастомный
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(Yii::$app->homeUrl . 'site/index');
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Действие для выхода из системы.
     * Метод сбрасывает статус аутентификации сразу и из памяти и из сессии.
     * И по умолчанию, будут также уничтожены все сессионные данные пользователя.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(Yii::$app->homeUrl . 'site/index');
    }

    /**
     * Действие для регистрации нового пользователя.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                // if (Yii::$app->getUser()->login($user)) {
                return $this->redirect(Yii::$app->homeUrl . 'site/index');
                // }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        Произошла ошибка во время обработки вашего запроса веб-сервером.
    </p>
    <p>
        Пожалуйста, свяжитесь с нами, если вы думаете, что это ошибка сервера. Спасибо.
    </p>

</div>

views/site/index.php
<?php
/* @var array $model \app\models\Book|\app\models\Course */

$this->title = 'Всё | Энциклопедия digital-рынка — мероприятия, компании, персоны,
    награды, курсы, издания, решения, технологии, ассоциации (Тэглайн)';
?>
<div class="site-index">
    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <table style="width: 100%; height: 40px;">
                    <tbody>
                    <tr>
                        <td style="vertical-align: middle;"><a
                                href="<?= '/books/index' ?>"><strong>Книги</strong></a></td>
                        <td
                            style="font-size: 13px; font-weight: normal; text-align: center; width: 35px; color: #808080; vertical-align: middle; height: 20px;"
                            title="Сортировка по алфавиту">А-Я&nbsp;<img src="/images/sort-alph.png">
                        </td>
                    </tr>
                    </tbody>
                </table>

                <div id="minBook" class="minBook">
                    <table cellpadding="5">
                        <tbody id="books">
                        <?php $x = 0 ?>
                        <?php foreach ($model["books"] as $book): ?>
                            <?php if ($x == 5) {
                                continue;
                            } ?>
                            <tr>
                                <td style="vertical-align:top;">
                                    <?php if (!empty($book->img)): ?>
                                        <a target="_blank" href="<?= $book->link ?>"
                                           title="<?= $book->author . ". " . $book->caption ?>">
                                            <img src="/images/icon/books/<?= $book->img ?>" width="30"
                                                 height="50">
                                        </a>
                                    <?php endif ?>
                                </td>
                                <td style="width: 240px; vertical-align:top;">
                                    <strong>&nbsp; <?= $book->author ?> </strong> <br>
                                    <?php if (!empty($book->link)): ?>
                                        <a target="_blank" href="<?= $book->link ?>">
                                            &nbsp; <?= $book->caption ?></a>
                                    <?php else: ?>
                                        <span>&nbsp; <?= $book->caption ?></span>
                                    <?php endif ?>
                                </td>
                            </tr>
                            <?php $x++ ?>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                    <br>
                </div>

                <div id="maxBook" class="maxBook" style="display: none;">
                    <table cellpadding="5">
                        <tbody id="books">
                        <?php foreach ($model["books"] as $book): ?>
                            <tr>
                                <td style="vertical-align:top;">
                                    <?php if (!empty($book->img)): ?>
                                        <a target="_blank" href="<?= $book->link ?>"
                                           title="<?= $book->author . ". " . $book->caption ?>">
                                            <img src="/images/icon/books/<?= $book->img ?>" width="30"
                                                 height="50">
                                        </a>
                                    <?php endif ?>
                                </td>
                                <td style="width: 240px; vertical-align:top;">
                                    <?php if (!empty($book->link)): ?>
                                        <strong>&nbsp; <?= $book->author ?> </strong> <br>
                                        <a target="_blank" href="<?= $book->link ?>">
                                            &nbsp; <?= $book->caption ?></a>
                                    <?php else: ?>
                                        <span>&nbsp; <?= $book->caption ?></span>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                    <br>
                </div>
                <div class="HideShowButton">
                    <a href="#" id="btn3" title="">
                        <span id="minTextBook" class="btn btn-default">
                            &nbsp;&nbsp;&nbsp;Показать ещё&nbsp;&nbsp;&nbsp;
                        </span>
                        <span id="maxTextBook" class="btn btn-default" style="display: none;">
                            &nbsp;&nbsp;&nbsp;Скрыть&nbsp;&nbsp;&nbsp;
                        </span>
                    </a>
                </div>
            </div>


            <div class="col-lg-4">
                <table style="width: 100%; height: 40px;">
                    <tbody>
                    <tr>
                        <td style="vertical-align: center;"><a
                                href="<?= '/courses/index' ?>"><strong>Курсы</strong></a></td>
                        <td style="width: 16px;" title="Сортировка по рейтингу"><img src="/images/sort-rating.png"></td>
                    </tr>
                    </tbody>
                </table>

                <div id="minCourse" class="minCourse">
                    <table cellpadding="5">
                        <tbody id="course">
                        <?php $x = 0 ?>
                        <?php foreach ($model["courses"] as $course): ?>
                            <?php if ($x == 3) {
                                continue;
                            } ?>
                            <tr>
                                <?php if (!empty($course->img)): ?>
                                    <td><img src="/images/icon/courses/<?= $course->img ?>" width="16"
                                             height="16"></td>
                                <?php else: ?>
                                    <td></td>
                                <?php endif ?>
                                <td>
                                    <?php if (!empty($course->link)): ?>
                                        <a target="_blank" href="<?= $course->link ?>">
                                            &nbsp; <?= $course->name ?></a>
                                    <?php else: ?>
                                        <span>&nbsp; <?= $course->name ?></span>
                                    <?php endif ?>
                                </td>
                            </tr>
                            <?php $x++ ?>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                    <br>
                </div>

                <div id="maxCourse" class="maxCourse" style="display: none;">
                    <table cellpadding="5">
                        <tbody id="course">
                        <?php foreach ($model["courses"] as $course): ?>
                            <tr>
                                <?php if (!empty($course->img)): ?>
                                    <td><img src="/images/icon/courses/<?= $course->img ?>" width="16"
                                             height="16"></td>
                                <?php else: ?>
                                    <td></td>
                                <?php endif ?>
                                <td>
                                    <?php if (!empty($course->link)): ?>
                                        <a target="_blank" href="<?= $course->link ?>">
                                            &nbsp; <?= $course->name ?></a>
                                    <?php else: ?>
                                        <span>&nbsp; <?= $course->name ?></span>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                    <br>
                </div>
                <div class="HideShowButton">
                    <a href="#" id="btnCourse" title="">
                        <span id="minTextCourse" class="btn btn-default">
                            &nbsp;&nbsp;&nbsp;Показать ещё&nbsp;&nbsp;&nbsp;
                        </span>
                        <span id="maxTextCourse" class="btn btn-default" style="display: none;">
                            &nbsp;&nbsp;&nbsp;Скрыть&nbsp;&nbsp;&nbsp;
                        </span>
                    </a>
                </div>

            </div>

        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для входа:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]) ?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true])->label('Логин') ?>

    <?= $form->field($model, 'password')->passwordInput()->label('Пароль') ?>

    <?= $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} Запомнить меня</div>\n
                       <div class=\"col-lg-8\">{error}</div>",
    ]) ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end() ?>

</div>

views/site/signup.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для регистрации:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']) ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true])->label('Логин') ?>

            <?= $form->field($model, 'password')->passwordInput()->label('Пароль') ?>

            <div class="form-group">
                <?= Html::submitButton('Зарегистрировать', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>

            <?php ActiveForm::end() ?>
        </div>
    </div>
</div>